spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: mysql

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true # false에서 true로 변경하여 Security와의 충돌 방지

  sql:
    init:
      mode: never

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}