spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # update, create
    defer-datasource-initialization: true

  # 로컬 테스트용
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#  h2:
#    console:
#      enabled: true

  # 서버 배포용
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always

app:
  auth:
    google:
      web-client-id: ${GOOGLE_CLIENT_ID}
jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}
  access-expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일

cloud:
  aws:
    region:
      static: ${CLOUD_AWS_REGION_STATIC:ap-northeast-2}
      auto: false
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:default_value}
      secret-key: ${AWS_SECRET_ACCESS_KEY:default_value}
    s3:
      enabled: true
      bucket: ${CLOUD_AWS_S3_BUCKET:dkfjfie}