spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create # update, create
    defer-datasource-initialization: true
  #  로컬 테스트용
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  # oauth2 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  h2:
    console:
      enabled: true